name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Format check with black
      run: |
        black --check --diff hq/ tests/

    - name: Import sorting check with isort
      run: |
        pip install isort
        isort --check-only --diff hq/ tests/

    - name: Security check with bandit
      run: |
        pip install bandit
        bandit -r hq/ -f json || true
